### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by onllm** [tonyd256/TDAudioPlayer#3]
Downloaded project, clicked run , got the following error

/Users/tony/dev/audioplayer-ios/TDAudioPlayer/TDAudioPlayer/Demo/Base.lproj/Main.storyboard: Interface Builder could not open the document "Main.storyboard" because it does not exist.

**Comment by richardgroves** [comment]
The Demo project in the repository should be runnable. The commit here - https://github.com/laptobbe/TDAudioPlayer/commit/99950e4ff19b147cb0a8157673044db12dd6dce6 - fixes the absolute storyboard path problem that @onllm found.

**Comment by tonyd256** [comment]
Sorry I've been away but things are merged now and it should work.
